ALTER TABLE ALCOHOL DROP FOREIGN KEY FK_ALCOHOL_CATEGORY_ID
ALTER TABLE ALCOHOL DROP FOREIGN KEY FK_ALCOHOL_user_Id
ALTER TABLE comments DROP FOREIGN KEY FK_comments_user_Id
ALTER TABLE comments DROP FOREIGN KEY FK_comments_alch_Id
ALTER TABLE likes DROP FOREIGN KEY FK_likes_COMMENT_ID
ALTER TABLE likes DROP FOREIGN KEY FK_likes_user_Id
ALTER TABLE likes DROP FOREIGN KEY FK_likes_ALCOHOL_ID
ALTER TABLE stars DROP FOREIGN KEY FK_stars_ALCOHOL_ID
ALTER TABLE stars DROP FOREIGN KEY FK_stars_user_Id
ALTER TABLE tags_ALCOHOL DROP FOREIGN KEY FK_tags_ALCOHOL_alcohols_ID
ALTER TABLE tags_ALCOHOL DROP FOREIGN KEY FK_tags_ALCOHOL_tags_ID
DROP TABLE ACCOUNT
DROP TABLE ALCOHOL
DROP TABLE CATEGORY
DROP TABLE comments
DROP TABLE likes
DROP TABLE stars
DROP TABLE tags
DROP TABLE tags_ALCOHOL
